mongodb:
  image: mongo
  ports:
    - "27017:27017"

mongo-seed:
  build: ./mongo-seed
  links:
    - mongodb

# subquip-backend:
#   build: .
#   ports:
#     - "3333:80"
#   links:
#     - mongodb:localhost
#   environment:
#     - ConnectionStrings.SubQuipConnection="mongodb://mongodb:27017/SubQuipDb"
