FROM mongo

COPY *.json /seed-data/
COPY *.sh /seed-data/

RUN echo http://nl.alpinelinux.org/alpine/edge/testing >> /etc/apk/repositories
RUN echo http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories
RUN apk add --no-cache dos2unix

RUN chmod +x /seed-data/entrypoint.sh

RUN dos2unix /seed-data/entrypoint.sh

ENTRYPOINT ["/seed-data/entrypoint.sh"]
CMD ["foreman", "start"]